"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: v2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dfirtrackapi_client
from dfirtrackapi_client.model.system import System


class TestSystem(unittest.TestCase):
    """System unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystem(self):
        """Test System"""
        # FIXME: construct object with mandatory attributes with example values
        # model = System()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
