"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: v2.4.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import dfirtrackapi_client
from dfirtrackapi_client.api.api_api import ApiApi  # noqa: E501


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self):
        self.api = ApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_artifact(self):
        """Test case for create_artifact

        """
        pass

    def test_create_artifacttype(self):
        """Test case for create_artifacttype

        """
        pass

    def test_create_auth_token(self):
        """Test case for create_auth_token

        """
        pass

    def test_create_case(self):
        """Test case for create_case

        """
        pass

    def test_create_casetype(self):
        """Test case for create_casetype

        """
        pass

    def test_create_company(self):
        """Test case for create_company

        """
        pass

    def test_create_contact(self):
        """Test case for create_contact

        """
        pass

    def test_create_division(self):
        """Test case for create_division

        """
        pass

    def test_create_dnsname(self):
        """Test case for create_dnsname

        """
        pass

    def test_create_domain(self):
        """Test case for create_domain

        """
        pass

    def test_create_domainuser(self):
        """Test case for create_domainuser

        """
        pass

    def test_create_headline(self):
        """Test case for create_headline

        """
        pass

    def test_create_ip(self):
        """Test case for create_ip

        """
        pass

    def test_create_location(self):
        """Test case for create_location

        """
        pass

    def test_create_note(self):
        """Test case for create_note

        """
        pass

    def test_create_os(self):
        """Test case for create_os

        """
        pass

    def test_create_osarch(self):
        """Test case for create_osarch

        """
        pass

    def test_create_reason(self):
        """Test case for create_reason

        """
        pass

    def test_create_recommendation(self):
        """Test case for create_recommendation

        """
        pass

    def test_create_reportitem(self):
        """Test case for create_reportitem

        """
        pass

    def test_create_serviceprovider(self):
        """Test case for create_serviceprovider

        """
        pass

    def test_create_system(self):
        """Test case for create_system

        """
        pass

    def test_create_systemtype(self):
        """Test case for create_systemtype

        """
        pass

    def test_create_systemuser(self):
        """Test case for create_systemuser

        """
        pass

    def test_create_tag(self):
        """Test case for create_tag

        """
        pass

    def test_create_task(self):
        """Test case for create_task

        """
        pass

    def test_create_taskname(self):
        """Test case for create_taskname

        """
        pass

    def test_list_analysisstatus(self):
        """Test case for list_analysisstatus

        """
        pass

    def test_list_artifactprioritys(self):
        """Test case for list_artifactprioritys

        """
        pass

    def test_list_artifacts(self):
        """Test case for list_artifacts

        """
        pass

    def test_list_artifactstatus(self):
        """Test case for list_artifactstatus

        """
        pass

    def test_list_artifacttypes(self):
        """Test case for list_artifacttypes

        """
        pass

    def test_list_caseprioritys(self):
        """Test case for list_caseprioritys

        """
        pass

    def test_list_cases(self):
        """Test case for list_cases

        """
        pass

    def test_list_casestatus(self):
        """Test case for list_casestatus

        """
        pass

    def test_list_casetypes(self):
        """Test case for list_casetypes

        """
        pass

    def test_list_companys(self):
        """Test case for list_companys

        """
        pass

    def test_list_contacts(self):
        """Test case for list_contacts

        """
        pass

    def test_list_divisions(self):
        """Test case for list_divisions

        """
        pass

    def test_list_dnsnames(self):
        """Test case for list_dnsnames

        """
        pass

    def test_list_domains(self):
        """Test case for list_domains

        """
        pass

    def test_list_domainusers(self):
        """Test case for list_domainusers

        """
        pass

    def test_list_headlines(self):
        """Test case for list_headlines

        """
        pass

    def test_list_ips(self):
        """Test case for list_ips

        """
        pass

    def test_list_locations(self):
        """Test case for list_locations

        """
        pass

    def test_list_notes(self):
        """Test case for list_notes

        """
        pass

    def test_list_notestatus(self):
        """Test case for list_notestatus

        """
        pass

    def test_list_os(self):
        """Test case for list_os

        """
        pass

    def test_list_osarchs(self):
        """Test case for list_osarchs

        """
        pass

    def test_list_reasons(self):
        """Test case for list_reasons

        """
        pass

    def test_list_recommendations(self):
        """Test case for list_recommendations

        """
        pass

    def test_list_reportitems(self):
        """Test case for list_reportitems

        """
        pass

    def test_list_serviceproviders(self):
        """Test case for list_serviceproviders

        """
        pass

    def test_list_systems(self):
        """Test case for list_systems

        """
        pass

    def test_list_systemstatus(self):
        """Test case for list_systemstatus

        """
        pass

    def test_list_systemtypes(self):
        """Test case for list_systemtypes

        """
        pass

    def test_list_systemusers(self):
        """Test case for list_systemusers

        """
        pass

    def test_list_tagcolors(self):
        """Test case for list_tagcolors

        """
        pass

    def test_list_tags(self):
        """Test case for list_tags

        """
        pass

    def test_list_tasknames(self):
        """Test case for list_tasknames

        """
        pass

    def test_list_taskprioritys(self):
        """Test case for list_taskprioritys

        """
        pass

    def test_list_tasks(self):
        """Test case for list_tasks

        """
        pass

    def test_list_taskstatus(self):
        """Test case for list_taskstatus

        """
        pass

    def test_partial_update_artifact(self):
        """Test case for partial_update_artifact

        """
        pass

    def test_partial_update_artifacttype(self):
        """Test case for partial_update_artifacttype

        """
        pass

    def test_partial_update_case(self):
        """Test case for partial_update_case

        """
        pass

    def test_partial_update_casetype(self):
        """Test case for partial_update_casetype

        """
        pass

    def test_partial_update_company(self):
        """Test case for partial_update_company

        """
        pass

    def test_partial_update_contact(self):
        """Test case for partial_update_contact

        """
        pass

    def test_partial_update_division(self):
        """Test case for partial_update_division

        """
        pass

    def test_partial_update_dnsname(self):
        """Test case for partial_update_dnsname

        """
        pass

    def test_partial_update_domain(self):
        """Test case for partial_update_domain

        """
        pass

    def test_partial_update_domainuser(self):
        """Test case for partial_update_domainuser

        """
        pass

    def test_partial_update_headline(self):
        """Test case for partial_update_headline

        """
        pass

    def test_partial_update_ip(self):
        """Test case for partial_update_ip

        """
        pass

    def test_partial_update_location(self):
        """Test case for partial_update_location

        """
        pass

    def test_partial_update_note(self):
        """Test case for partial_update_note

        """
        pass

    def test_partial_update_os(self):
        """Test case for partial_update_os

        """
        pass

    def test_partial_update_osarch(self):
        """Test case for partial_update_osarch

        """
        pass

    def test_partial_update_reason(self):
        """Test case for partial_update_reason

        """
        pass

    def test_partial_update_recommendation(self):
        """Test case for partial_update_recommendation

        """
        pass

    def test_partial_update_reportitem(self):
        """Test case for partial_update_reportitem

        """
        pass

    def test_partial_update_serviceprovider(self):
        """Test case for partial_update_serviceprovider

        """
        pass

    def test_partial_update_system(self):
        """Test case for partial_update_system

        """
        pass

    def test_partial_update_systemtype(self):
        """Test case for partial_update_systemtype

        """
        pass

    def test_partial_update_systemuser(self):
        """Test case for partial_update_systemuser

        """
        pass

    def test_partial_update_tag(self):
        """Test case for partial_update_tag

        """
        pass

    def test_partial_update_task(self):
        """Test case for partial_update_task

        """
        pass

    def test_partial_update_taskname(self):
        """Test case for partial_update_taskname

        """
        pass

    def test_retrieve_analysisstatus(self):
        """Test case for retrieve_analysisstatus

        """
        pass

    def test_retrieve_artifact(self):
        """Test case for retrieve_artifact

        """
        pass

    def test_retrieve_artifactpriority(self):
        """Test case for retrieve_artifactpriority

        """
        pass

    def test_retrieve_artifactstatus(self):
        """Test case for retrieve_artifactstatus

        """
        pass

    def test_retrieve_artifacttype(self):
        """Test case for retrieve_artifacttype

        """
        pass

    def test_retrieve_case(self):
        """Test case for retrieve_case

        """
        pass

    def test_retrieve_casepriority(self):
        """Test case for retrieve_casepriority

        """
        pass

    def test_retrieve_casestatus(self):
        """Test case for retrieve_casestatus

        """
        pass

    def test_retrieve_casetype(self):
        """Test case for retrieve_casetype

        """
        pass

    def test_retrieve_company(self):
        """Test case for retrieve_company

        """
        pass

    def test_retrieve_contact(self):
        """Test case for retrieve_contact

        """
        pass

    def test_retrieve_division(self):
        """Test case for retrieve_division

        """
        pass

    def test_retrieve_dnsname(self):
        """Test case for retrieve_dnsname

        """
        pass

    def test_retrieve_domain(self):
        """Test case for retrieve_domain

        """
        pass

    def test_retrieve_domainuser(self):
        """Test case for retrieve_domainuser

        """
        pass

    def test_retrieve_headline(self):
        """Test case for retrieve_headline

        """
        pass

    def test_retrieve_ip(self):
        """Test case for retrieve_ip

        """
        pass

    def test_retrieve_location(self):
        """Test case for retrieve_location

        """
        pass

    def test_retrieve_note(self):
        """Test case for retrieve_note

        """
        pass

    def test_retrieve_notestatus(self):
        """Test case for retrieve_notestatus

        """
        pass

    def test_retrieve_os(self):
        """Test case for retrieve_os

        """
        pass

    def test_retrieve_osarch(self):
        """Test case for retrieve_osarch

        """
        pass

    def test_retrieve_reason(self):
        """Test case for retrieve_reason

        """
        pass

    def test_retrieve_recommendation(self):
        """Test case for retrieve_recommendation

        """
        pass

    def test_retrieve_reportitem(self):
        """Test case for retrieve_reportitem

        """
        pass

    def test_retrieve_serviceprovider(self):
        """Test case for retrieve_serviceprovider

        """
        pass

    def test_retrieve_system(self):
        """Test case for retrieve_system

        """
        pass

    def test_retrieve_systemstatus(self):
        """Test case for retrieve_systemstatus

        """
        pass

    def test_retrieve_systemtype(self):
        """Test case for retrieve_systemtype

        """
        pass

    def test_retrieve_systemuser(self):
        """Test case for retrieve_systemuser

        """
        pass

    def test_retrieve_tag(self):
        """Test case for retrieve_tag

        """
        pass

    def test_retrieve_tagcolor(self):
        """Test case for retrieve_tagcolor

        """
        pass

    def test_retrieve_task(self):
        """Test case for retrieve_task

        """
        pass

    def test_retrieve_taskname(self):
        """Test case for retrieve_taskname

        """
        pass

    def test_retrieve_taskpriority(self):
        """Test case for retrieve_taskpriority

        """
        pass

    def test_retrieve_taskstatus(self):
        """Test case for retrieve_taskstatus

        """
        pass

    def test_update_artifact(self):
        """Test case for update_artifact

        """
        pass

    def test_update_artifacttype(self):
        """Test case for update_artifacttype

        """
        pass

    def test_update_case(self):
        """Test case for update_case

        """
        pass

    def test_update_casetype(self):
        """Test case for update_casetype

        """
        pass

    def test_update_company(self):
        """Test case for update_company

        """
        pass

    def test_update_contact(self):
        """Test case for update_contact

        """
        pass

    def test_update_division(self):
        """Test case for update_division

        """
        pass

    def test_update_dnsname(self):
        """Test case for update_dnsname

        """
        pass

    def test_update_domain(self):
        """Test case for update_domain

        """
        pass

    def test_update_domainuser(self):
        """Test case for update_domainuser

        """
        pass

    def test_update_headline(self):
        """Test case for update_headline

        """
        pass

    def test_update_ip(self):
        """Test case for update_ip

        """
        pass

    def test_update_location(self):
        """Test case for update_location

        """
        pass

    def test_update_note(self):
        """Test case for update_note

        """
        pass

    def test_update_os(self):
        """Test case for update_os

        """
        pass

    def test_update_osarch(self):
        """Test case for update_osarch

        """
        pass

    def test_update_reason(self):
        """Test case for update_reason

        """
        pass

    def test_update_recommendation(self):
        """Test case for update_recommendation

        """
        pass

    def test_update_reportitem(self):
        """Test case for update_reportitem

        """
        pass

    def test_update_serviceprovider(self):
        """Test case for update_serviceprovider

        """
        pass

    def test_update_system(self):
        """Test case for update_system

        """
        pass

    def test_update_systemtype(self):
        """Test case for update_systemtype

        """
        pass

    def test_update_systemuser(self):
        """Test case for update_systemuser

        """
        pass

    def test_update_tag(self):
        """Test case for update_tag

        """
        pass

    def test_update_task(self):
        """Test case for update_task

        """
        pass

    def test_update_taskname(self):
        """Test case for update_taskname

        """
        pass


if __name__ == '__main__':
    unittest.main()
