"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: v1.5.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dfirtrackapi_client
from dfirtrackapi_client.model.notestatus import Notestatus


class TestNotestatus(unittest.TestCase):
    """Notestatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotestatus(self):
        """Test Notestatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Notestatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
