# coding: utf-8

"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import dfirtrackapi_client
from dfirtrackapi_client.models.case import Case  # noqa: E501
from dfirtrackapi_client.rest import ApiException

class TestCase(unittest.TestCase):
    """Case unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Case
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = dfirtrackapi_client.models.case.Case()  # noqa: E501
        if include_optional :
            return Case(
                case_id = 56, 
                case_name = '0', 
                case_is_incident = True, 
                case_created_by_user_id = 56, 
                case_create_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return Case(
                case_name = '0',
                case_is_incident = True,
                case_created_by_user_id = 56,
        )

    def testCase(self):
        """Test Case"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
