"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: v2.4.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dfirtrackapi_client
from dfirtrackapi_client.model.artifactpriority import Artifactpriority


class TestArtifactpriority(unittest.TestCase):
    """Artifactpriority unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArtifactpriority(self):
        """Test Artifactpriority"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Artifactpriority()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
