"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: v2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dfirtrackapi_client
from dfirtrackapi_client.model.analysisstatus import Analysisstatus


class TestAnalysisstatus(unittest.TestCase):
    """Analysisstatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalysisstatus(self):
        """Test Analysisstatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Analysisstatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
