"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: v2.4.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dfirtrackapi_client
from dfirtrackapi_client.model.division import Division


class TestDivision(unittest.TestCase):
    """Division unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDivision(self):
        """Test Division"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Division()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
