# coding: utf-8

"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import dfirtrackapi_client
from dfirtrackapi_client.models.systemuser import Systemuser  # noqa: E501
from dfirtrackapi_client.rest import ApiException

class TestSystemuser(unittest.TestCase):
    """Systemuser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Systemuser
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = dfirtrackapi_client.models.systemuser.Systemuser()  # noqa: E501
        if include_optional :
            return Systemuser(
                systemuser_id = 56, 
                systemuser_name = '0', 
                system = 56, 
                systemuser_lastlogon_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                systemuser_is_systemadmin = True
            )
        else :
            return Systemuser(
                systemuser_name = '0',
                system = 56,
        )

    def testSystemuser(self):
        """Test Systemuser"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
