"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: v1.5.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dfirtrackapi_client
from dfirtrackapi_client.model.note import Note


class TestNote(unittest.TestCase):
    """Note unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNote(self):
        """Test Note"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Note()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
