# coding: utf-8

"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import dfirtrackapi_client
from dfirtrackapi_client.models.ip import Ip  # noqa: E501
from dfirtrackapi_client.rest import ApiException

class TestIp(unittest.TestCase):
    """Ip unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Ip
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = dfirtrackapi_client.models.ip.Ip()  # noqa: E501
        if include_optional :
            return Ip(
                ip_id = 56, 
                ip_ip = '0'
            )
        else :
            return Ip(
                ip_ip = '0',
        )

    def testIp(self):
        """Test Ip"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
