"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: v2.4.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dfirtrackapi_client
from dfirtrackapi_client.model.headline import Headline


class TestHeadline(unittest.TestCase):
    """Headline unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHeadline(self):
        """Test Headline"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Headline()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
