"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: v2.4.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dfirtrackapi_client
from dfirtrackapi_client.model.artifacttype import Artifacttype


class TestArtifacttype(unittest.TestCase):
    """Artifacttype unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArtifacttype(self):
        """Test Artifacttype"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Artifacttype()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
