"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: v2.4.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dfirtrackapi_client
from dfirtrackapi_client.model.systemstatus import Systemstatus


class TestSystemstatus(unittest.TestCase):
    """Systemstatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemstatus(self):
        """Test Systemstatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Systemstatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
