"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: v2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dfirtrackapi_client
from dfirtrackapi_client.model.os import Os


class TestOs(unittest.TestCase):
    """Os unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOs(self):
        """Test Os"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Os()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
