"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: v2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dfirtrackapi_client
from dfirtrackapi_client.model.case import Case


class TestCase(unittest.TestCase):
    """Case unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCase(self):
        """Test Case"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Case()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
