"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: v1.2.1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from dfirtrackapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


class Case(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('case_name',): {
            'max_length': 50,
        },
        ('case_id_external',): {
            'max_length': 50,
        },
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'case_name': (str,),  # noqa: E501
            'case_is_incident': (bool,),  # noqa: E501
            'case_created_by_user_id': (int,),  # noqa: E501
            'case_id': (int,),  # noqa: E501
            'case_id_external': (str, none_type,),  # noqa: E501
            'casepriority': (int,),  # noqa: E501
            'casestatus': (int,),  # noqa: E501
            'casetype': (int, none_type,),  # noqa: E501
            'tag': ([int],),  # noqa: E501
            'case_start_time': (datetime, none_type,),  # noqa: E501
            'case_end_time': (datetime, none_type,),  # noqa: E501
            'case_create_time': (datetime,),  # noqa: E501
            'case_modified_by_user_id': (int, none_type,),  # noqa: E501
            'case_modify_time': (datetime,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'case_name': 'case_name',  # noqa: E501
        'case_is_incident': 'case_is_incident',  # noqa: E501
        'case_created_by_user_id': 'case_created_by_user_id',  # noqa: E501
        'case_id': 'case_id',  # noqa: E501
        'case_id_external': 'case_id_external',  # noqa: E501
        'casepriority': 'casepriority',  # noqa: E501
        'casestatus': 'casestatus',  # noqa: E501
        'casetype': 'casetype',  # noqa: E501
        'tag': 'tag',  # noqa: E501
        'case_start_time': 'case_start_time',  # noqa: E501
        'case_end_time': 'case_end_time',  # noqa: E501
        'case_create_time': 'case_create_time',  # noqa: E501
        'case_modified_by_user_id': 'case_modified_by_user_id',  # noqa: E501
        'case_modify_time': 'case_modify_time',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, case_name, case_is_incident, case_created_by_user_id, *args, **kwargs):  # noqa: E501
        """Case - a model defined in OpenAPI

        Args:
            case_name (str):
            case_is_incident (bool):
            case_created_by_user_id (int):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            case_id (int): [optional]  # noqa: E501
            case_id_external (str, none_type): [optional]  # noqa: E501
            casepriority (int): [optional]  # noqa: E501
            casestatus (int): [optional]  # noqa: E501
            casetype (int, none_type): [optional]  # noqa: E501
            tag ([int]): [optional]  # noqa: E501
            case_start_time (datetime, none_type): [optional]  # noqa: E501
            case_end_time (datetime, none_type): [optional]  # noqa: E501
            case_create_time (datetime): [optional]  # noqa: E501
            case_modified_by_user_id (int, none_type): [optional]  # noqa: E501
            case_modify_time (datetime): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.case_name = case_name
        self.case_is_incident = case_is_incident
        self.case_created_by_user_id = case_created_by_user_id
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
