# coding: utf-8

"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from dfirtrackapi_client.configuration import Configuration


class Contact(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'contact_id': 'int',
        'contact_name': 'str',
        'contact_email': 'str',
        'contact_phone': 'str'
    }

    attribute_map = {
        'contact_id': 'contact_id',
        'contact_name': 'contact_name',
        'contact_email': 'contact_email',
        'contact_phone': 'contact_phone'
    }

    def __init__(self, contact_id=None, contact_name=None, contact_email=None, contact_phone=None, local_vars_configuration=None):  # noqa: E501
        """Contact - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._contact_id = None
        self._contact_name = None
        self._contact_email = None
        self._contact_phone = None
        self.discriminator = None

        if contact_id is not None:
            self.contact_id = contact_id
        self.contact_name = contact_name
        self.contact_email = contact_email
        self.contact_phone = contact_phone

    @property
    def contact_id(self):
        """Gets the contact_id of this Contact.  # noqa: E501


        :return: The contact_id of this Contact.  # noqa: E501
        :rtype: int
        """
        return self._contact_id

    @contact_id.setter
    def contact_id(self, contact_id):
        """Sets the contact_id of this Contact.


        :param contact_id: The contact_id of this Contact.  # noqa: E501
        :type: int
        """

        self._contact_id = contact_id

    @property
    def contact_name(self):
        """Gets the contact_name of this Contact.  # noqa: E501


        :return: The contact_name of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._contact_name

    @contact_name.setter
    def contact_name(self, contact_name):
        """Sets the contact_name of this Contact.


        :param contact_name: The contact_name of this Contact.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and contact_name is None:  # noqa: E501
            raise ValueError("Invalid value for `contact_name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                contact_name is not None and len(contact_name) > 100):
            raise ValueError("Invalid value for `contact_name`, length must be less than or equal to `100`")  # noqa: E501

        self._contact_name = contact_name

    @property
    def contact_email(self):
        """Gets the contact_email of this Contact.  # noqa: E501


        :return: The contact_email of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._contact_email

    @contact_email.setter
    def contact_email(self, contact_email):
        """Sets the contact_email of this Contact.


        :param contact_email: The contact_email of this Contact.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and contact_email is None:  # noqa: E501
            raise ValueError("Invalid value for `contact_email`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                contact_email is not None and len(contact_email) > 100):
            raise ValueError("Invalid value for `contact_email`, length must be less than or equal to `100`")  # noqa: E501

        self._contact_email = contact_email

    @property
    def contact_phone(self):
        """Gets the contact_phone of this Contact.  # noqa: E501


        :return: The contact_phone of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._contact_phone

    @contact_phone.setter
    def contact_phone(self, contact_phone):
        """Sets the contact_phone of this Contact.


        :param contact_phone: The contact_phone of this Contact.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                contact_phone is not None and len(contact_phone) > 50):
            raise ValueError("Invalid value for `contact_phone`, length must be less than or equal to `50`")  # noqa: E501

        self._contact_phone = contact_phone

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Contact):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Contact):
            return True

        return self.to_dict() != other.to_dict()
