# coding: utf-8

"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from dfirtrackapi_client.configuration import Configuration


class Division(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'division_id': 'int',
        'division_name': 'str'
    }

    attribute_map = {
        'division_id': 'division_id',
        'division_name': 'division_name'
    }

    def __init__(self, division_id=None, division_name=None, local_vars_configuration=None):  # noqa: E501
        """Division - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._division_id = None
        self._division_name = None
        self.discriminator = None

        if division_id is not None:
            self.division_id = division_id
        self.division_name = division_name

    @property
    def division_id(self):
        """Gets the division_id of this Division.  # noqa: E501


        :return: The division_id of this Division.  # noqa: E501
        :rtype: int
        """
        return self._division_id

    @division_id.setter
    def division_id(self, division_id):
        """Sets the division_id of this Division.


        :param division_id: The division_id of this Division.  # noqa: E501
        :type: int
        """

        self._division_id = division_id

    @property
    def division_name(self):
        """Gets the division_name of this Division.  # noqa: E501


        :return: The division_name of this Division.  # noqa: E501
        :rtype: str
        """
        return self._division_name

    @division_name.setter
    def division_name(self, division_name):
        """Sets the division_name of this Division.


        :param division_name: The division_name of this Division.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and division_name is None:  # noqa: E501
            raise ValueError("Invalid value for `division_name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                division_name is not None and len(division_name) > 50):
            raise ValueError("Invalid value for `division_name`, length must be less than or equal to `50`")  # noqa: E501

        self._division_name = division_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Division):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Division):
            return True

        return self.to_dict() != other.to_dict()
