# coding: utf-8

"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from dfirtrackapi_client.configuration import Configuration


class Dnsname(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'dnsname_id': 'int',
        'dnsname_name': 'str',
        'domain': 'int'
    }

    attribute_map = {
        'dnsname_id': 'dnsname_id',
        'dnsname_name': 'dnsname_name',
        'domain': 'domain'
    }

    def __init__(self, dnsname_id=None, dnsname_name=None, domain=None, local_vars_configuration=None):  # noqa: E501
        """Dnsname - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._dnsname_id = None
        self._dnsname_name = None
        self._domain = None
        self.discriminator = None

        if dnsname_id is not None:
            self.dnsname_id = dnsname_id
        self.dnsname_name = dnsname_name
        self.domain = domain

    @property
    def dnsname_id(self):
        """Gets the dnsname_id of this Dnsname.  # noqa: E501


        :return: The dnsname_id of this Dnsname.  # noqa: E501
        :rtype: int
        """
        return self._dnsname_id

    @dnsname_id.setter
    def dnsname_id(self, dnsname_id):
        """Sets the dnsname_id of this Dnsname.


        :param dnsname_id: The dnsname_id of this Dnsname.  # noqa: E501
        :type: int
        """

        self._dnsname_id = dnsname_id

    @property
    def dnsname_name(self):
        """Gets the dnsname_name of this Dnsname.  # noqa: E501


        :return: The dnsname_name of this Dnsname.  # noqa: E501
        :rtype: str
        """
        return self._dnsname_name

    @dnsname_name.setter
    def dnsname_name(self, dnsname_name):
        """Sets the dnsname_name of this Dnsname.


        :param dnsname_name: The dnsname_name of this Dnsname.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and dnsname_name is None:  # noqa: E501
            raise ValueError("Invalid value for `dnsname_name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                dnsname_name is not None and len(dnsname_name) > 100):
            raise ValueError("Invalid value for `dnsname_name`, length must be less than or equal to `100`")  # noqa: E501

        self._dnsname_name = dnsname_name

    @property
    def domain(self):
        """Gets the domain of this Dnsname.  # noqa: E501


        :return: The domain of this Dnsname.  # noqa: E501
        :rtype: int
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this Dnsname.


        :param domain: The domain of this Dnsname.  # noqa: E501
        :type: int
        """

        self._domain = domain

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Dnsname):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Dnsname):
            return True

        return self.to_dict() != other.to_dict()
