# coding: utf-8

"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from dfirtrackapi_client.configuration import Configuration


class Domainuser(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'domainuser_id': 'int',
        'domainuser_name': 'str',
        'domain': 'int',
        'domainuser_is_domainadmin': 'bool'
    }

    attribute_map = {
        'domainuser_id': 'domainuser_id',
        'domainuser_name': 'domainuser_name',
        'domain': 'domain',
        'domainuser_is_domainadmin': 'domainuser_is_domainadmin'
    }

    def __init__(self, domainuser_id=None, domainuser_name=None, domain=None, domainuser_is_domainadmin=None, local_vars_configuration=None):  # noqa: E501
        """Domainuser - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._domainuser_id = None
        self._domainuser_name = None
        self._domain = None
        self._domainuser_is_domainadmin = None
        self.discriminator = None

        if domainuser_id is not None:
            self.domainuser_id = domainuser_id
        self.domainuser_name = domainuser_name
        self.domain = domain
        self.domainuser_is_domainadmin = domainuser_is_domainadmin

    @property
    def domainuser_id(self):
        """Gets the domainuser_id of this Domainuser.  # noqa: E501


        :return: The domainuser_id of this Domainuser.  # noqa: E501
        :rtype: int
        """
        return self._domainuser_id

    @domainuser_id.setter
    def domainuser_id(self, domainuser_id):
        """Sets the domainuser_id of this Domainuser.


        :param domainuser_id: The domainuser_id of this Domainuser.  # noqa: E501
        :type: int
        """

        self._domainuser_id = domainuser_id

    @property
    def domainuser_name(self):
        """Gets the domainuser_name of this Domainuser.  # noqa: E501


        :return: The domainuser_name of this Domainuser.  # noqa: E501
        :rtype: str
        """
        return self._domainuser_name

    @domainuser_name.setter
    def domainuser_name(self, domainuser_name):
        """Sets the domainuser_name of this Domainuser.


        :param domainuser_name: The domainuser_name of this Domainuser.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and domainuser_name is None:  # noqa: E501
            raise ValueError("Invalid value for `domainuser_name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                domainuser_name is not None and len(domainuser_name) > 50):
            raise ValueError("Invalid value for `domainuser_name`, length must be less than or equal to `50`")  # noqa: E501

        self._domainuser_name = domainuser_name

    @property
    def domain(self):
        """Gets the domain of this Domainuser.  # noqa: E501


        :return: The domain of this Domainuser.  # noqa: E501
        :rtype: int
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this Domainuser.


        :param domain: The domain of this Domainuser.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and domain is None:  # noqa: E501
            raise ValueError("Invalid value for `domain`, must not be `None`")  # noqa: E501

        self._domain = domain

    @property
    def domainuser_is_domainadmin(self):
        """Gets the domainuser_is_domainadmin of this Domainuser.  # noqa: E501


        :return: The domainuser_is_domainadmin of this Domainuser.  # noqa: E501
        :rtype: bool
        """
        return self._domainuser_is_domainadmin

    @domainuser_is_domainadmin.setter
    def domainuser_is_domainadmin(self, domainuser_is_domainadmin):
        """Sets the domainuser_is_domainadmin of this Domainuser.


        :param domainuser_is_domainadmin: The domainuser_is_domainadmin of this Domainuser.  # noqa: E501
        :type: bool
        """

        self._domainuser_is_domainadmin = domainuser_is_domainadmin

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Domainuser):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Domainuser):
            return True

        return self.to_dict() != other.to_dict()
