# coding: utf-8

"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from dfirtrackapi_client.configuration import Configuration


class Ip(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ip_id': 'int',
        'ip_ip': 'str'
    }

    attribute_map = {
        'ip_id': 'ip_id',
        'ip_ip': 'ip_ip'
    }

    def __init__(self, ip_id=None, ip_ip=None, local_vars_configuration=None):  # noqa: E501
        """Ip - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._ip_id = None
        self._ip_ip = None
        self.discriminator = None

        if ip_id is not None:
            self.ip_id = ip_id
        self.ip_ip = ip_ip

    @property
    def ip_id(self):
        """Gets the ip_id of this Ip.  # noqa: E501


        :return: The ip_id of this Ip.  # noqa: E501
        :rtype: int
        """
        return self._ip_id

    @ip_id.setter
    def ip_id(self, ip_id):
        """Sets the ip_id of this Ip.


        :param ip_id: The ip_id of this Ip.  # noqa: E501
        :type: int
        """

        self._ip_id = ip_id

    @property
    def ip_ip(self):
        """Gets the ip_ip of this Ip.  # noqa: E501


        :return: The ip_ip of this Ip.  # noqa: E501
        :rtype: str
        """
        return self._ip_ip

    @ip_ip.setter
    def ip_ip(self, ip_ip):
        """Sets the ip_ip of this Ip.


        :param ip_ip: The ip_ip of this Ip.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and ip_ip is None:  # noqa: E501
            raise ValueError("Invalid value for `ip_ip`, must not be `None`")  # noqa: E501

        self._ip_ip = ip_ip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Ip):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Ip):
            return True

        return self.to_dict() != other.to_dict()
