# coding: utf-8

"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from dfirtrackapi_client.configuration import Configuration


class Serviceprovider(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'serviceprovider_id': 'int',
        'serviceprovider_name': 'str'
    }

    attribute_map = {
        'serviceprovider_id': 'serviceprovider_id',
        'serviceprovider_name': 'serviceprovider_name'
    }

    def __init__(self, serviceprovider_id=None, serviceprovider_name=None, local_vars_configuration=None):  # noqa: E501
        """Serviceprovider - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._serviceprovider_id = None
        self._serviceprovider_name = None
        self.discriminator = None

        if serviceprovider_id is not None:
            self.serviceprovider_id = serviceprovider_id
        self.serviceprovider_name = serviceprovider_name

    @property
    def serviceprovider_id(self):
        """Gets the serviceprovider_id of this Serviceprovider.  # noqa: E501


        :return: The serviceprovider_id of this Serviceprovider.  # noqa: E501
        :rtype: int
        """
        return self._serviceprovider_id

    @serviceprovider_id.setter
    def serviceprovider_id(self, serviceprovider_id):
        """Sets the serviceprovider_id of this Serviceprovider.


        :param serviceprovider_id: The serviceprovider_id of this Serviceprovider.  # noqa: E501
        :type: int
        """

        self._serviceprovider_id = serviceprovider_id

    @property
    def serviceprovider_name(self):
        """Gets the serviceprovider_name of this Serviceprovider.  # noqa: E501


        :return: The serviceprovider_name of this Serviceprovider.  # noqa: E501
        :rtype: str
        """
        return self._serviceprovider_name

    @serviceprovider_name.setter
    def serviceprovider_name(self, serviceprovider_name):
        """Sets the serviceprovider_name of this Serviceprovider.


        :param serviceprovider_name: The serviceprovider_name of this Serviceprovider.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and serviceprovider_name is None:  # noqa: E501
            raise ValueError("Invalid value for `serviceprovider_name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                serviceprovider_name is not None and len(serviceprovider_name) > 50):
            raise ValueError("Invalid value for `serviceprovider_name`, length must be less than or equal to `50`")  # noqa: E501

        self._serviceprovider_name = serviceprovider_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Serviceprovider):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Serviceprovider):
            return True

        return self.to_dict() != other.to_dict()
