# coding: utf-8

"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from dfirtrackapi_client.configuration import Configuration


class Systemstatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'systemstatus_id': 'int',
        'systemstatus_name': 'str'
    }

    attribute_map = {
        'systemstatus_id': 'systemstatus_id',
        'systemstatus_name': 'systemstatus_name'
    }

    def __init__(self, systemstatus_id=None, systemstatus_name=None, local_vars_configuration=None):  # noqa: E501
        """Systemstatus - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._systemstatus_id = None
        self._systemstatus_name = None
        self.discriminator = None

        if systemstatus_id is not None:
            self.systemstatus_id = systemstatus_id
        self.systemstatus_name = systemstatus_name

    @property
    def systemstatus_id(self):
        """Gets the systemstatus_id of this Systemstatus.  # noqa: E501


        :return: The systemstatus_id of this Systemstatus.  # noqa: E501
        :rtype: int
        """
        return self._systemstatus_id

    @systemstatus_id.setter
    def systemstatus_id(self, systemstatus_id):
        """Sets the systemstatus_id of this Systemstatus.


        :param systemstatus_id: The systemstatus_id of this Systemstatus.  # noqa: E501
        :type: int
        """

        self._systemstatus_id = systemstatus_id

    @property
    def systemstatus_name(self):
        """Gets the systemstatus_name of this Systemstatus.  # noqa: E501


        :return: The systemstatus_name of this Systemstatus.  # noqa: E501
        :rtype: str
        """
        return self._systemstatus_name

    @systemstatus_name.setter
    def systemstatus_name(self, systemstatus_name):
        """Sets the systemstatus_name of this Systemstatus.


        :param systemstatus_name: The systemstatus_name of this Systemstatus.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and systemstatus_name is None:  # noqa: E501
            raise ValueError("Invalid value for `systemstatus_name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                systemstatus_name is not None and len(systemstatus_name) > 30):
            raise ValueError("Invalid value for `systemstatus_name`, length must be less than or equal to `30`")  # noqa: E501

        self._systemstatus_name = systemstatus_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Systemstatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Systemstatus):
            return True

        return self.to_dict() != other.to_dict()
