# coding: utf-8

"""
    DFIRTrack

    OpenAPI 3 - Documentation of DFIRTrack API  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from dfirtrackapi_client.configuration import Configuration


class Taskname(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'taskname_id': 'int',
        'taskname_name': 'str'
    }

    attribute_map = {
        'taskname_id': 'taskname_id',
        'taskname_name': 'taskname_name'
    }

    def __init__(self, taskname_id=None, taskname_name=None, local_vars_configuration=None):  # noqa: E501
        """Taskname - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._taskname_id = None
        self._taskname_name = None
        self.discriminator = None

        if taskname_id is not None:
            self.taskname_id = taskname_id
        self.taskname_name = taskname_name

    @property
    def taskname_id(self):
        """Gets the taskname_id of this Taskname.  # noqa: E501


        :return: The taskname_id of this Taskname.  # noqa: E501
        :rtype: int
        """
        return self._taskname_id

    @taskname_id.setter
    def taskname_id(self, taskname_id):
        """Sets the taskname_id of this Taskname.


        :param taskname_id: The taskname_id of this Taskname.  # noqa: E501
        :type: int
        """

        self._taskname_id = taskname_id

    @property
    def taskname_name(self):
        """Gets the taskname_name of this Taskname.  # noqa: E501


        :return: The taskname_name of this Taskname.  # noqa: E501
        :rtype: str
        """
        return self._taskname_name

    @taskname_name.setter
    def taskname_name(self, taskname_name):
        """Sets the taskname_name of this Taskname.


        :param taskname_name: The taskname_name of this Taskname.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and taskname_name is None:  # noqa: E501
            raise ValueError("Invalid value for `taskname_name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                taskname_name is not None and len(taskname_name) > 50):
            raise ValueError("Invalid value for `taskname_name`, length must be less than or equal to `50`")  # noqa: E501

        self._taskname_name = taskname_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Taskname):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Taskname):
            return True

        return self.to_dict() != other.to_dict()
